-- 家庭記帳 App — 初始 schema
-- 對照 specs/13-資料庫Schema.md。金額一律整數（新台幣元）。
-- 一律不使用 DELETE：is_active（可逆停用）、is_deleted（軟刪除）。

begin;

/* ── members ──────────────────────────────────────────── */
create table if not exists members (
  id                integer generated by default as identity primary key,
  name              text    not null,
  account           text    not null,
  role              text    not null,
  color             char(7) not null,
  joined_month      char(7) not null,
  is_active         boolean not null default true,
  password_hash     text,
  first_login_at    timestamptz,
  reset_code        char(6),
  failed_attempts   integer not null default 0,
  locked_until      timestamptz,
  constraint members_account_key   unique (account),
  constraint members_role_check    check (role in ('admin', 'member')),
  constraint members_month_check   check (joined_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  constraint members_color_check   check (color ~* '^#[0-9a-f]{6}$'),
  constraint members_code_check    check (reset_code is null or reset_code ~ '^\d{6}$')
);

/* ── main_categories ──────────────────────────────────── */
create table if not exists main_categories (
  id            integer generated by default as identity primary key,
  name          text    not null,
  icon          text    not null,
  type          text    not null,
  nature        text,
  sort_order    integer not null,
  is_active     boolean not null default true,
  is_system     boolean not null default false,
  active_from   char(7),
  archived_from char(7),
  constraint main_categories_type_check   check (type in ('expense', 'income')),
  constraint main_categories_nature_check check (
    (type = 'income'  and nature is null) or
    (type = 'expense' and nature in ('floating', 'fixed'))
  ),
  -- 停用年月不得早於啟用年月
  constraint main_categories_life_check check (
    archived_from is null or active_from is null or archived_from >= active_from
  )
);

/* ── sub_categories ───────────────────────────────────── */
create table if not exists sub_categories (
  id               integer generated by default as identity primary key,
  main_category_id integer not null references main_categories (id) on delete restrict,
  name             text    not null,
  sort_order       integer not null,
  is_active        boolean not null default true,
  -- 歸屬主分類只在新增時決定，不可搬移（specs/11）
  constraint sub_categories_name_key unique (main_category_id, name)
);

/* ── subscriptions ────────────────────────────────────── */
create table if not exists subscriptions (
  id               integer generated by default as identity primary key,
  name             text    not null,
  amount           integer not null,
  cycle            text    not null,
  next_charge_date date    not null,
  -- 原本的扣款日：遇月底不足只在該月夾齊（1/31 → 2/28），下一個足月份回到原日（3/31）
  charge_day       integer not null,
  main_category_id integer not null references main_categories (id) on delete restrict,
  payer_id         integer not null references members (id)         on delete restrict,
  is_active        boolean not null default true,
  constraint subscriptions_amount_check check (amount > 0),
  constraint subscriptions_cycle_check  check (cycle in ('monthly', 'yearly')),
  constraint subscriptions_day_check    check (charge_day between 1 and 31)
);

/* ── transactions ─────────────────────────────────────── */
create table if not exists transactions (
  id                     integer generated by default as identity primary key,
  type                   text    not null,
  main_category_id       integer references main_categories (id) on delete restrict,
  sub_category_id        integer references sub_categories (id)  on delete restrict,
  amount                 integer not null,
  date                   date    not null,
  payer_id               integer not null references members (id) on delete restrict,
  note             text,
  -- 分類名稱快照：記帳當下凍結，分類日後改名不影響歷史紀錄顯示
  main_category_name text,
  sub_category_name  text,
  created_at             timestamptz not null default now(),
  is_deleted             boolean not null default false,
  source_subscription_id integer references subscriptions (id) on delete set null,
  constraint transactions_type_check   check (type in ('expense', 'income')),
  constraint transactions_amount_check check (amount > 0)
);

-- 所有查詢都帶 is_deleted = false，不為已刪資料建索引
create index if not exists transactions_date_idx
  on transactions (date desc) where is_deleted = false;
create index if not exists transactions_category_idx
  on transactions (main_category_id, date) where is_deleted = false;
create index if not exists transactions_payer_idx
  on transactions (payer_id, date) where is_deleted = false;

-- 訂閱扣款的冪等保證：同一筆訂閱同一期只能有一筆交易。
-- 手動 mark-paid 與 Cron 自動扣款共用這道約束，重複觸發會被 onConflictDoNothing 吞掉。
create unique index if not exists transactions_subscription_period_idx
  on transactions (source_subscription_id, date)
  where source_subscription_id is not null and is_deleted = false;

/* ── transaction_revisions ────────────────────────────── */
create table if not exists transaction_revisions (
  id             integer generated by default as identity primary key,
  transaction_id integer not null references transactions (id) on delete cascade,
  edited_by      integer not null references members (id)      on delete restrict,
  edited_at      timestamptz not null default now(),
  field          text not null,
  before         text not null,
  after          text not null,
  -- type 與 payer_id 不可修改，故不會出現在此
  constraint transaction_revisions_field_check check (
    field in ('mainCategoryId', 'subCategoryId', 'amount', 'date', 'note')
  )
);

create index if not exists transaction_revisions_tx_idx
  on transaction_revisions (transaction_id, edited_at desc);

/* ── budgets ──────────────────────────────────────────── */
create table if not exists budgets (
  id               integer generated by default as identity primary key,
  month            char(7) not null,
  main_category_id integer not null references main_categories (id) on delete restrict,
  amount           integer not null,
  -- 「沿用上月」的 upsert 依據
  constraint budgets_month_category_key unique (month, main_category_id),
  constraint budgets_amount_check check (amount > 0),
  constraint budgets_month_check  check (month ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

/* ── subscription_revisions ───────────────────────────── */
create table if not exists subscription_revisions (
  id              integer generated by default as identity primary key,
  subscription_id integer not null references subscriptions (id) on delete cascade,
  effective_from  char(7) not null,
  amount          integer not null,
  cycle           text    not null,
  constraint subscription_revisions_key unique (subscription_id, effective_from),
  constraint subscription_revisions_amount_check check (amount > 0),
  constraint subscription_revisions_cycle_check  check (cycle in ('monthly', 'yearly')),
  constraint subscription_revisions_month_check  check (effective_from ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

/* ── year_extra_expenses ──────────────────────────────── */
-- 年度額外支出不分攤到個別月份，僅在年度彙整頁計入
create table if not exists year_extra_expenses (
  id               integer generated by default as identity primary key,
  year             integer not null,
  name             text    not null,
  amount           integer not null,
  main_category_id integer not null references main_categories (id) on delete restrict,
  payer_id         integer not null references members (id)         on delete restrict,
  constraint year_extra_amount_check check (amount > 0),
  constraint year_extra_year_check   check (year between 2000 and 2100)
);

create index if not exists year_extra_year_idx on year_extra_expenses (year);

/* ── RLS：全表 deny-all ───────────────────────────────── */
-- 前端不直連 Supabase；後端持 service role key 會繞過 RLS。
-- 這裡不建任何 policy，純粹作為金鑰外流時的最後一道防線。
alter table members                enable row level security;
alter table main_categories        enable row level security;
alter table sub_categories         enable row level security;
alter table transactions           enable row level security;
alter table transaction_revisions  enable row level security;
alter table budgets                enable row level security;
alter table subscriptions          enable row level security;
alter table subscription_revisions enable row level security;
alter table year_extra_expenses    enable row level security;

commit;
